### PR TITLE
Fix teleport to nether even if portalsdefaulttonether is false.

### PR DESCRIPTION
**Pull request by benwoo1110**
See my comments at https://github.com/Multiverse/Multiverse-Portals/pull/584#issuecomment-831842373

### CODE REVIEW

**Comment by nicegamer7** [comment]
Is the permission check used anywhere?

**Comment by benwoo1110** [comment]
Do you mean for `getPortal` method? It is used in PlayerMoveEvent as well

**Comment by benwoo1110** [comment]
Or do you mean if permission is checked later on in the PlayerPortalEvent? 😅 

https://github.com/Multiverse/Multiverse-Portals/blob/882b29f2cf40eeaacb07bf8e4d846aef6c5ca227/src/main/java/com/onarandombox/MultiversePortals/listeners/MVPPlayerListener.java#L271-L277

**Comment by nicegamer7** [comment]
Yeah I mean `getPortal` with the permission check.

My question is: Is there any use for checking permission in `getPortal`?

**Comment by benwoo1110** [comment]
In events such as `PlayerBucketFillEvent`, it looks like it's useful there. Bcu only ppl with access perms should be able to change its fill

https://github.com/Multiverse/Multiverse-Portals/blob/882b29f2cf40eeaacb07bf8e4d846aef6c5ca227/src/main/java/com/onarandombox/MultiversePortals/listeners/MVPPlayerListener.java#L67-L89

**Comment by nicegamer7** [comment]
Ah okay, sounds good then.

**Comment by benwoo1110** [comment]
Oh btw this fix will only work when you combine it with #584

**Review by nicegamer7 — APPROVED** [review]
LGTM 👍

**Pull request merged**
