### PR TITLE
Update WorldEdit integration for BlockVector3

### PR DESCRIPTION
**Pull request by electronicboy**
if anybody would like to have a copy of this before it's merged, builds are available here:
https://keybase.pub/electronicboy/builds/multiverse/portals/Multiverse-Portals-2.5.2-SNAPSHOT.jar

### CODE REVIEW

**Comment by lifehome** [comment]
Vouch, this build and code is tested working on Paper 1.13.2-R0.1 build 474.

**Comment by Rocologo** [comment]
Seems to work on SpigoMC 1.13.2 too.

**Comment by lifehome** [comment]
Tag @dumptruckman to review on this PR, as it is very useful to fix the broken build.

**Comment by FernFerret** [comment]
I saw this PR come in. I'll review this once I have a computer that has enough ram to spin up a server with my other projects.

**Comment by Futschel** [comment]
Is MVP 2.5.0-b751 or even mvp 3.0.0 compatible with worldedit 7.0 ?

**Comment by dumptruckman** [comment]
I believe that's exactly what this fixes.

**Pull request merged**
