### PR TITLE
mvp list: print one portal per line; sort alphabetically

### PR DESCRIPTION
**Pull request by hintron**
Hello,

I found that `mvp list` was not super useful in space-delimited, wrap-around form. So here's a patch that makes each portal show up on its own line with some optional refactor patches. Each commit compiles, and I tested the output in both 

On a related note, the docs don't show the `[FILTER]` option in https://github.com/Multiverse/Multiverse-Core/wiki/Command-Reference-(Portals)#list. I'm not sure if I'm able to edit that or not, but I would be happy to.

See https://github.com/Multiverse/Multiverse-Portals/blob/c189f2d3fc726263f72bf41f60cff1fbe1772c03/src/main/java/com/onarandombox/MultiversePortals/commands/ListCommand.java#L25.

### CODE REVIEW

**Comment by FernFerret** [comment]
Hey @hintron, thanks for this. I was never super happy with the portals list command but ended up swapping the colors so they could be read in one line.

I looked over your PR and it looks fine for the most part, but I'm concerned about the lack of a pager. It seems to me that the portals will quickly scroll off the screen once you get more than a few. Is this something you've considered?

**Comment by hintron** [comment]
@FernFerret Thanks for the quick response.

I think a pager would be cool. I did happen to see #48, so I assumed that a pager implementation/`PaginatedCommand` class did not yet exist. I figured that for now, we could just document the `[FILTER]` option with some good examples to show how a user can keep the output from overflowing past the screen, and then add in paging when it gets implemented. I didn't check, but if PaginatedCommand exists I'll gladly look to incorporate it as well.

**Comment by hintron** [comment]
If you still think the original wrap-around behavior is useful, maybe we can add some kind of option flag to toggle between the two modes of output.

**Comment by hintron** [comment]
If you are concerned about backwards compatibility, what if we kept `mvpl` as what it shows today (plus sorting), and then add an `mvpll` command that shows one per line? It would be analogous to the common `ll` alias compared with `ls` in Linux.

**Comment by EbonJaeger** [comment]
Having multiple forms of output is pretty pointless and adds needless complexity.

**Comment by FernFerret** [comment]
Yes, I agree, Stick with one form of output. If we're going to change this, my only request is that it be able to display greater than or equal to the previous form.

So if I could display:
```
a b c d e f g h i j k l m
```

In the previous, I wouldn't want to just be able to display:
```
j
k
l
m
```

I swear we use one elsewhere but can't remember. Also, this isn't a *critical* feature but is more cosmetic than anything else.

I am not concerned with backward compatibility since the original one was  hacked by me quickly because I didn't want to deal with a pager at the time.

**Comment by hintron** [comment]
It looks like the help, list, and anchor commands in Multiverse Core are paged. They use the`PaginatedCoreCommand` class which extends the `PaginatedCommand` class. Let me rework the patch to use that.

**Comment by hintron** [comment]
I'm seeing an issue converting `mvp list` into a paginated command. `mvp list` has some custom arg parsing logic to support both a world filter and a name filter simultaneously. Though it's undocumented, the functionality looks like this:

    mvp list [world] [filter]

The PaginatedCommand's `getPageAndFilter()` function does arg parsing, but only allows for a single filter and a page argument. Which means it will take a lot of extra logic to support this:

    mvp list [page] [world] [filter]

An option is to simply remove the additional filter and do this:

    mvp list [page] [world]

Since that extra filter was undocumented, it probably wouldn't hurt to get rid of it at this point. I find that extra filter to be of marginal benefit anyways. What do you think?

**Comment by dumptruckman** [comment]
I'm okay with removing the filter option in favor of paging.

**Comment by hintron** [comment]
Ok. I'll try to find some time to get paging working with this command.

**Comment by nicegamer7** [comment]
Not sure why GitHub closed this. I changed the branch to `main` before deleting `master`... but I guess I was moving to quickly. Sorry about that.

**Pull request closed without merging**
